name: vertex_ai_cookbook
description: "Firebase Vertex AI Cookbook Sample"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.9
  uuid: ^4.5.1
  # flutter_ai_toolkit: ^0.1.6
  flutter_ai_toolkit:
    git: https://github.com/csells/flutter_ai_toolkit.git
  gap: ^3.0.1
  firebase_vertexai: ^0.2.3+4
  flutter_markdown: ^0.7.3+2
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes_default.json
